<!DOCTYPE HTML>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title>429</title>
		<style type="text/css">
:root{--text-color:#c5c8c6;--bg-color:#1d1f21}
@media (prefers-color-scheme:light){:root{--text-color:#333;--bg-color:#fff}}
a,a:visited{color:var(--text-color)}
body,html{height:100%%;text-align:center}
body{display:flex;flex-direction:column;background-color:var(--bg-color);color:var(--text-color);font-family:Helvetica,Arial,sans-serif;max-width:60em;margin:0 auto;padding: 0 20px}
code{background-color:#dfdfdf30;border-radius:4px;padding:0 3px;color:#ff6590}
.pt{padding-top:30vh;display:flex;align-items:center;word-break:break-all;justify-content: center;}
img,h3{margin:0 0 5px 0;font-weight:normal}
footer{font-size:x-small;margin-top:auto;padding:10px;text-align:center;border-top:1px solid #80808040;padding:10px}
		</style>
	</head>
	<body>
		<h3 class="pt">
			%[var(txn.lang_json),json_query($."Slow down, you look like a robot\.")]
		</h3>
		<footer>
			<p>Node: <code>%[env(RAY_ID)]</code></p>
			<p>%[var(txn.lang_json),json_query($.Performance & security by BasedFlare)]</p>
		</footer>
	</body>
</html>

